// Copyright 2026 Jeremy Edwards
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/ufs.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SymlinkHandling controls whether a lookup follows a symbolic link to its
// target or reports on the link itself.
type SymlinkHandling int32

const (
	// Equivalent to SYMLINK_HANDLING_FOLLOW.
	SymlinkHandling_SYMLINK_HANDLING_UNSPECIFIED SymlinkHandling = 0
	// Follow the symbolic link and describe its target. Equivalent to
	// [ufs.ReadFS.Stat] / [fs.Stat].
	SymlinkHandling_SYMLINK_HANDLING_FOLLOW SymlinkHandling = 1
	// Do not follow the symbolic link; describe the link itself. Equivalent to
	// [fs.ReadLinkFS.Lstat].
	SymlinkHandling_SYMLINK_HANDLING_NO_FOLLOW SymlinkHandling = 2
)

// Enum value maps for SymlinkHandling.
var (
	SymlinkHandling_name = map[int32]string{
		0: "SYMLINK_HANDLING_UNSPECIFIED",
		1: "SYMLINK_HANDLING_FOLLOW",
		2: "SYMLINK_HANDLING_NO_FOLLOW",
	}
	SymlinkHandling_value = map[string]int32{
		"SYMLINK_HANDLING_UNSPECIFIED": 0,
		"SYMLINK_HANDLING_FOLLOW":      1,
		"SYMLINK_HANDLING_NO_FOLLOW":   2,
	}
)

func (x SymlinkHandling) Enum() *SymlinkHandling {
	p := new(SymlinkHandling)
	*p = x
	return p
}

func (x SymlinkHandling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymlinkHandling) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ufs_proto_enumTypes[0].Descriptor()
}

func (SymlinkHandling) Type() protoreflect.EnumType {
	return &file_proto_ufs_proto_enumTypes[0]
}

func (x SymlinkHandling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymlinkHandling.Descriptor instead.
func (SymlinkHandling) EnumDescriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{0}
}

// FilePermissions captures the access and type flags of a single node in a
// backend-agnostic form, so a client need not know which OS the backend uses.
// It tracks individual flags rather than any one OS's permission scheme: a
// backend that does not report a flag simply leaves it unset.
type FilePermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file can be read.
	Read bool `protobuf:"varint,1,opt,name=read" json:"read,omitempty"`
	// The file can be written.
	Write bool `protobuf:"varint,2,opt,name=write" json:"write,omitempty"`
	// The file can be executed.
	Execute bool `protobuf:"varint,3,opt,name=execute" json:"execute,omitempty"`
	// The entry is a directory.
	Dir bool `protobuf:"varint,4,opt,name=dir" json:"dir,omitempty"`
	// The entry is a symbolic link rather than a regular file or directory.
	Symlink bool `protobuf:"varint,5,opt,name=symlink" json:"symlink,omitempty"`
	// Group flag. Semantics are defined by the providing backend.
	Group         bool `protobuf:"varint,6,opt,name=group" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePermissions) Reset() {
	*x = FilePermissions{}
	mi := &file_proto_ufs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePermissions) ProtoMessage() {}

func (x *FilePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePermissions.ProtoReflect.Descriptor instead.
func (*FilePermissions) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{0}
}

func (x *FilePermissions) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *FilePermissions) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

func (x *FilePermissions) GetExecute() bool {
	if x != nil {
		return x.Execute
	}
	return false
}

func (x *FilePermissions) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

func (x *FilePermissions) GetSymlink() bool {
	if x != nil {
		return x.Symlink
	}
	return false
}

func (x *FilePermissions) GetGroup() bool {
	if x != nil {
		return x.Group
	}
	return false
}

// FileAttributes is a per-node metadata record whose `name` references the
// [File] resource. Beyond that reference it carries the node's identity (uid),
// its descriptive attributes (absolute path, size, access/type flags), and its
// lifecycle timestamps.
type FileAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The [File] resource this record describes, by its name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The node's absolute, OS-level path as known by the backend. Empty for
	// backends with no native absolute path (e.g. object storage).
	AbsolutePath string `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath" json:"absolute_path,omitempty"`
	// Length in bytes for regular files; system-dependent for others.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// The access and type flags for the node, see [FilePermissions].
	Permission *FilePermissions `protobuf:"bytes,4,opt,name=permission" json:"permission,omitempty"`
	// Creation time, as reported by backends that track it (e.g. NTFS). AIP-148
	// standard field; empty if the backend does not provide a creation time.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	// The time the node was last modified, as returned by [fs.FileInfo.ModTime]
	// (the standard AIP-148 `update_time` field). Empty if the backend does not
	// report one.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	// Last access time, as reported by backends that track it (a file-system
	// concept, not an AIP-148 standard field).
	AccessTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=access_time,json=accessTime" json:"access_time,omitempty"`
	// A stable, system-assigned unique identifier for the node (e.g. the inode
	// number or a backend object ID), per AIP-148. Empty for backends that have
	// no such identifier.
	Uid           string `protobuf:"bytes,8,opt,name=uid" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttributes) Reset() {
	*x = FileAttributes{}
	mi := &file_proto_ufs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttributes) ProtoMessage() {}

func (x *FileAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttributes.ProtoReflect.Descriptor instead.
func (*FileAttributes) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{1}
}

func (x *FileAttributes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileAttributes) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *FileAttributes) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttributes) GetPermission() *FilePermissions {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *FileAttributes) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *FileAttributes) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *FileAttributes) GetAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTime
	}
	return nil
}

func (x *FileAttributes) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// File is the resource representation of a node (regular file or directory)
// in a [ufs.ReadFS] tree. It mirrors [ufs.FileInfo].
//
// File names follow [fs.ValidPath]: forward-slash separated, no leading
// slash, no "." or ".." components. The root directory is always ".".
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the file, relative to the root of the file system.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Length in bytes for regular files; system-dependent for others.
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	// File mode bits, as defined by Go's io/fs.FileMode.
	Mode uint32 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	// The time the file was last modified.
	ModTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime" json:"mod_time,omitempty"`
	// Whether the file is a directory. Equivalent to mode's directory bit.
	IsDir         bool `protobuf:"varint,5,opt,name=is_dir,json=isDir" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_ufs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *File) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *File) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

// FileSystemInfo describes the file system as a whole. It is a singleton
// resource (AIP-156): there is exactly one, and it has no name field.
type FileSystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI that identifies this file system, as returned by [ufs.ReadFS.URI].
	// Can be passed to ufs.New to reconstruct an equivalent file system.
	// Empty if the file system has no meaningful URI.
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// A human-readable description of how the file system is composed, as
	// returned by [ufs.ReadFS.String]. Intended for debugging and logging, not
	// programmatic use.
	Description   string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSystemInfo) Reset() {
	*x = FileSystemInfo{}
	mi := &file_proto_ufs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSystemInfo) ProtoMessage() {}

func (x *FileSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSystemInfo.ProtoReflect.Descriptor instead.
func (*FileSystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{3}
}

func (x *FileSystemInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FileSystemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// BoltFileRecord is the value the bolt driver (drivers/boltfs) stores under
// each file's key in its backing bbolt database. The node's path is not part
// of the record: it is implied by the bbolt key (and the chain of nested
// buckets leading to it). BoltFileRecord is internal to that driver and is
// not part of the RPC surface.
type BoltFileRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File mode bits, as defined by Go's io/fs.FileMode.
	Mode uint32 `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	// The time the file was last modified.
	ModTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=mod_time,json=modTime" json:"mod_time,omitempty"`
	// Raw file content.
	Content       []byte `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoltFileRecord) Reset() {
	*x = BoltFileRecord{}
	mi := &file_proto_ufs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoltFileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoltFileRecord) ProtoMessage() {}

func (x *BoltFileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoltFileRecord.ProtoReflect.Descriptor instead.
func (*BoltFileRecord) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{4}
}

func (x *BoltFileRecord) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *BoltFileRecord) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *BoltFileRecord) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the file to retrieve.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Whether to follow a trailing symbolic link at name. Defaults to
	// SYMLINK_HANDLING_FOLLOW.
	SymlinkHandling SymlinkHandling `protobuf:"varint,2,opt,name=symlink_handling,json=symlinkHandling,enum=cloudfra.ufs.SymlinkHandling" json:"symlink_handling,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_ufs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFileRequest) GetSymlinkHandling() SymlinkHandling {
	if x != nil {
		return x.SymlinkHandling
	}
	return SymlinkHandling_SYMLINK_HANDLING_UNSPECIFIED
}

type ListFilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory whose immediate children should be listed. "." lists the
	// root directory.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// The maximum number of files to return. The service may return fewer
	// than this value. If unspecified, the server picks a reasonable default.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	// A page token received from a previous ListFiles call, used to retrieve
	// the next page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_ufs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFilesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The immediate children of the requested parent directory, sorted by
	// filename, as returned by [ufs.ReadFS.ReadDir].
	Files []*File `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	// A token that can be sent as page_token to retrieve the next page. Empty
	// if there are no more files.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_ufs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the file to read.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The byte offset to start reading from. 0 reads from the start of the
	// file.
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	// The maximum number of bytes to return across the whole stream. 0 (the
	// default) reads to the end of the file.
	Limit         int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_ufs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A chunk of file content. Chunks are delivered in order starting at
	// offset and are concatenated by the client to reconstruct the requested
	// range.
	Data          []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_ufs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{9}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path of the symbolic link to resolve.
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkRequest) Reset() {
	*x = ReadLinkRequest{}
	mi := &file_proto_ufs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkRequest) ProtoMessage() {}

func (x *ReadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkRequest.ProtoReflect.Descriptor instead.
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{10}
}

func (x *ReadLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadLinkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The destination path of the symbolic link, as returned by
	// [ufs.ReadFS.ReadLink]. May be relative to the link's directory.
	Target        string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkResponse) Reset() {
	*x = ReadLinkResponse{}
	mi := &file_proto_ufs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkResponse) ProtoMessage() {}

func (x *ReadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkResponse.ProtoReflect.Descriptor instead.
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{11}
}

func (x *ReadLinkResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type GetFileSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileSystemInfoRequest) Reset() {
	*x = GetFileSystemInfoRequest{}
	mi := &file_proto_ufs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileSystemInfoRequest) ProtoMessage() {}

func (x *GetFileSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ufs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_ufs_proto_rawDescGZIP(), []int{12}
}

var File_proto_ufs_proto protoreflect.FileDescriptor

const file_proto_ufs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ufs.proto\x12\fcloudfra.ufs\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x0fFilePermissions\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05write\x12\x18\n" +
	"\aexecute\x18\x03 \x01(\bR\aexecute\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\bR\x03dir\x12\x18\n" +
	"\asymlink\x18\x05 \x01(\bR\asymlink\x12\x14\n" +
	"\x05group\x18\x06 \x01(\bR\x05group\"\xa6\x03\n" +
	"\x0eFileAttributes\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14ufs.cloudfra.io/FileR\x04name\x12(\n" +
	"\rabsolute_path\x18\x02 \x01(\tB\x03\xe0A\x03R\fabsolutePath\x12\x17\n" +
	"\x04size\x18\x03 \x01(\x03B\x03\xe0A\x03R\x04size\x12B\n" +
	"\n" +
	"permission\x18\x04 \x01(\v2\x1d.cloudfra.ufs.FilePermissionsB\x03\xe0A\x03R\n" +
	"permission\x12@\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12@\n" +
	"\vaccess_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"accessTime\x12\x15\n" +
	"\x03uid\x18\b \x01(\tB\x03\xe0A\x03R\x03uid\"\xdc\x01\n" +
	"\x04File\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x03B\x03\xe0A\x03R\x04size\x12\x17\n" +
	"\x04mode\x18\x03 \x01(\rB\x03\xe0A\x03R\x04mode\x12:\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\amodTime\x12\x1a\n" +
	"\x06is_dir\x18\x05 \x01(\bB\x03\xe0A\x03R\x05isDir:1\xeaA.\n" +
	"\x14ufs.cloudfra.io/File\x12\t{path=**}*\x05files2\x04file\"N\n" +
	"\x0eFileSystemInfo\x12\x15\n" +
	"\x03uri\x18\x01 \x01(\tB\x03\xe0A\x03R\x03uri\x12%\n" +
	"\vdescription\x18\x02 \x01(\tB\x03\xe0A\x03R\vdescription\"u\n" +
	"\x0eBoltFileRecord\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x8c\x01\n" +
	"\x0eGetFileRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14ufs.cloudfra.io/FileR\x04name\x12H\n" +
	"\x10symlink_handling\x18\x02 \x01(\x0e2\x1d.cloudfra.ufs.SymlinkHandlingR\x0fsymlinkHandling\"\x84\x01\n" +
	"\x10ListFilesRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14ufs.cloudfra.io/FileR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"e\n" +
	"\x11ListFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.cloudfra.ufs.FileR\x05files\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"q\n" +
	"\x0fReadFileRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14ufs.cloudfra.io/FileR\x04name\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"&\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"C\n" +
	"\x0fReadLinkRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14ufs.cloudfra.io/FileR\x04name\"*\n" +
	"\x10ReadLinkResponse\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x1a\n" +
	"\x18GetFileSystemInfoRequest*p\n" +
	"\x0fSymlinkHandling\x12 \n" +
	"\x1cSYMLINK_HANDLING_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SYMLINK_HANDLING_FOLLOW\x10\x01\x12\x1e\n" +
	"\x1aSYMLINK_HANDLING_NO_FOLLOW\x10\x022\x88\x04\n" +
	"\x06ReadFS\x12R\n" +
	"\aGetFile\x12\x1c.cloudfra.ufs.GetFileRequest\x1a\x12.cloudfra.ufs.File\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/{name=**}\x12_\n" +
	"\tListFiles\x12\x1e.cloudfra.ufs.ListFilesRequest\x1a\x1f.cloudfra.ufs.ListFilesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/files\x12g\n" +
	"\bReadFile\x12\x1d.cloudfra.ufs.ReadFileRequest\x1a\x1e.cloudfra.ufs.ReadFileResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/{name=**}:read0\x01\x12i\n" +
	"\bReadLink\x12\x1d.cloudfra.ufs.ReadLinkRequest\x1a\x1e.cloudfra.ufs.ReadLinkResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{name=**}:readLink\x12u\n" +
	"\x11GetFileSystemInfo\x12&.cloudfra.ufs.GetFileSystemInfoRequest\x1a\x1c.cloudfra.ufs.FileSystemInfo\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/fileSystemInfoB)Z\x1dgithub.com/cloudfra/ufs/proto\x92\x03\a\xd2>\x02\x10\x01\b\x02b\beditionsp\xe9\a"

var (
	file_proto_ufs_proto_rawDescOnce sync.Once
	file_proto_ufs_proto_rawDescData []byte
)

func file_proto_ufs_proto_rawDescGZIP() []byte {
	file_proto_ufs_proto_rawDescOnce.Do(func() {
		file_proto_ufs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ufs_proto_rawDesc), len(file_proto_ufs_proto_rawDesc)))
	})
	return file_proto_ufs_proto_rawDescData
}

var file_proto_ufs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ufs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_ufs_proto_goTypes = []any{
	(SymlinkHandling)(0),             // 0: cloudfra.ufs.SymlinkHandling
	(*FilePermissions)(nil),          // 1: cloudfra.ufs.FilePermissions
	(*FileAttributes)(nil),           // 2: cloudfra.ufs.FileAttributes
	(*File)(nil),                     // 3: cloudfra.ufs.File
	(*FileSystemInfo)(nil),           // 4: cloudfra.ufs.FileSystemInfo
	(*BoltFileRecord)(nil),           // 5: cloudfra.ufs.BoltFileRecord
	(*GetFileRequest)(nil),           // 6: cloudfra.ufs.GetFileRequest
	(*ListFilesRequest)(nil),         // 7: cloudfra.ufs.ListFilesRequest
	(*ListFilesResponse)(nil),        // 8: cloudfra.ufs.ListFilesResponse
	(*ReadFileRequest)(nil),          // 9: cloudfra.ufs.ReadFileRequest
	(*ReadFileResponse)(nil),         // 10: cloudfra.ufs.ReadFileResponse
	(*ReadLinkRequest)(nil),          // 11: cloudfra.ufs.ReadLinkRequest
	(*ReadLinkResponse)(nil),         // 12: cloudfra.ufs.ReadLinkResponse
	(*GetFileSystemInfoRequest)(nil), // 13: cloudfra.ufs.GetFileSystemInfoRequest
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_proto_ufs_proto_depIdxs = []int32{
	1,  // 0: cloudfra.ufs.FileAttributes.permission:type_name -> cloudfra.ufs.FilePermissions
	14, // 1: cloudfra.ufs.FileAttributes.create_time:type_name -> google.protobuf.Timestamp
	14, // 2: cloudfra.ufs.FileAttributes.update_time:type_name -> google.protobuf.Timestamp
	14, // 3: cloudfra.ufs.FileAttributes.access_time:type_name -> google.protobuf.Timestamp
	14, // 4: cloudfra.ufs.File.mod_time:type_name -> google.protobuf.Timestamp
	14, // 5: cloudfra.ufs.BoltFileRecord.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 6: cloudfra.ufs.GetFileRequest.symlink_handling:type_name -> cloudfra.ufs.SymlinkHandling
	3,  // 7: cloudfra.ufs.ListFilesResponse.files:type_name -> cloudfra.ufs.File
	6,  // 8: cloudfra.ufs.ReadFS.GetFile:input_type -> cloudfra.ufs.GetFileRequest
	7,  // 9: cloudfra.ufs.ReadFS.ListFiles:input_type -> cloudfra.ufs.ListFilesRequest
	9,  // 10: cloudfra.ufs.ReadFS.ReadFile:input_type -> cloudfra.ufs.ReadFileRequest
	11, // 11: cloudfra.ufs.ReadFS.ReadLink:input_type -> cloudfra.ufs.ReadLinkRequest
	13, // 12: cloudfra.ufs.ReadFS.GetFileSystemInfo:input_type -> cloudfra.ufs.GetFileSystemInfoRequest
	3,  // 13: cloudfra.ufs.ReadFS.GetFile:output_type -> cloudfra.ufs.File
	8,  // 14: cloudfra.ufs.ReadFS.ListFiles:output_type -> cloudfra.ufs.ListFilesResponse
	10, // 15: cloudfra.ufs.ReadFS.ReadFile:output_type -> cloudfra.ufs.ReadFileResponse
	12, // 16: cloudfra.ufs.ReadFS.ReadLink:output_type -> cloudfra.ufs.ReadLinkResponse
	4,  // 17: cloudfra.ufs.ReadFS.GetFileSystemInfo:output_type -> cloudfra.ufs.FileSystemInfo
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ufs_proto_init() }
func file_proto_ufs_proto_init() {
	if File_proto_ufs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ufs_proto_rawDesc), len(file_proto_ufs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ufs_proto_goTypes,
		DependencyIndexes: file_proto_ufs_proto_depIdxs,
		EnumInfos:         file_proto_ufs_proto_enumTypes,
		MessageInfos:      file_proto_ufs_proto_msgTypes,
	}.Build()
	File_proto_ufs_proto = out.File
	file_proto_ufs_proto_goTypes = nil
	file_proto_ufs_proto_depIdxs = nil
}
