// Copyright 2026 Jeremy Edwards
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/ufs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReadFS_GetFile_FullMethodName           = "/cloudfra.ufs.ReadFS/GetFile"
	ReadFS_ListFiles_FullMethodName         = "/cloudfra.ufs.ReadFS/ListFiles"
	ReadFS_ReadFile_FullMethodName          = "/cloudfra.ufs.ReadFS/ReadFile"
	ReadFS_ReadLink_FullMethodName          = "/cloudfra.ufs.ReadFS/ReadLink"
	ReadFS_GetFileSystemInfo_FullMethodName = "/cloudfra.ufs.ReadFS/GetFileSystemInfo"
)

// ReadFSClient is the client API for ReadFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReadFS exposes the read-only surface of a [ufs.ReadFS] file system over
// RPC: metadata lookup, directory listing, symbolic link resolution, and
// streaming file content.
//
// ufs.ReadFS's io.Closer.Close is intentionally not exposed here: it tears
// down the entire underlying file system (e.g. unmounting or disconnecting
// a cloud storage client) rather than acting on a single request, and is a
// server-lifecycle concern rather than a per-client one.
//
// Errors follow standard gRPC canonical codes: a lookup for a path that does
// not exist returns NOT_FOUND (wrapping fs.ErrNotExist), and an operation
// forbidden by the backend returns PERMISSION_DENIED (wrapping
// fs.ErrPermission).
type ReadFSClient interface {
	// GetFile returns metadata for the file at name. Equivalent to
	// [ufs.ReadFS.Stat], or [ufs.ReadFS.Lstat] when symlink_handling is
	// SYMLINK_HANDLING_NO_FOLLOW.
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*File, error)
	// ListFiles returns the immediate children of a directory. Equivalent to
	// [ufs.ReadFS.ReadDir].
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// ReadFile streams the content of the file at name. Equivalent to opening
	// the file via [ufs.ReadFS.Open] and reading its contents, or
	// [ufs.ReadFS.ReadFile] when the client buffers the full stream.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileResponse], error)
	// ReadLink returns the destination of the symbolic link at name.
	// Equivalent to [ufs.ReadFS.ReadLink].
	ReadLink(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error)
	// GetFileSystemInfo describes the file system itself. Equivalent to
	// [ufs.ReadFS.URI] and [ufs.ReadFS.String].
	GetFileSystemInfo(ctx context.Context, in *GetFileSystemInfoRequest, opts ...grpc.CallOption) (*FileSystemInfo, error)
}

type readFSClient struct {
	cc grpc.ClientConnInterface
}

func NewReadFSClient(cc grpc.ClientConnInterface) ReadFSClient {
	return &readFSClient{cc}
}

func (c *readFSClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*File, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(File)
	err := c.cc.Invoke(ctx, ReadFS_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readFSClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, ReadFS_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readFSClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReadFS_ServiceDesc.Streams[0], ReadFS_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, ReadFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReadFS_ReadFileClient = grpc.ServerStreamingClient[ReadFileResponse]

func (c *readFSClient) ReadLink(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLinkResponse)
	err := c.cc.Invoke(ctx, ReadFS_ReadLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readFSClient) GetFileSystemInfo(ctx context.Context, in *GetFileSystemInfoRequest, opts ...grpc.CallOption) (*FileSystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileSystemInfo)
	err := c.cc.Invoke(ctx, ReadFS_GetFileSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadFSServer is the server API for ReadFS service.
// All implementations must embed UnimplementedReadFSServer
// for forward compatibility.
//
// ReadFS exposes the read-only surface of a [ufs.ReadFS] file system over
// RPC: metadata lookup, directory listing, symbolic link resolution, and
// streaming file content.
//
// ufs.ReadFS's io.Closer.Close is intentionally not exposed here: it tears
// down the entire underlying file system (e.g. unmounting or disconnecting
// a cloud storage client) rather than acting on a single request, and is a
// server-lifecycle concern rather than a per-client one.
//
// Errors follow standard gRPC canonical codes: a lookup for a path that does
// not exist returns NOT_FOUND (wrapping fs.ErrNotExist), and an operation
// forbidden by the backend returns PERMISSION_DENIED (wrapping
// fs.ErrPermission).
type ReadFSServer interface {
	// GetFile returns metadata for the file at name. Equivalent to
	// [ufs.ReadFS.Stat], or [ufs.ReadFS.Lstat] when symlink_handling is
	// SYMLINK_HANDLING_NO_FOLLOW.
	GetFile(context.Context, *GetFileRequest) (*File, error)
	// ListFiles returns the immediate children of a directory. Equivalent to
	// [ufs.ReadFS.ReadDir].
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// ReadFile streams the content of the file at name. Equivalent to opening
	// the file via [ufs.ReadFS.Open] and reading its contents, or
	// [ufs.ReadFS.ReadFile] when the client buffers the full stream.
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileResponse]) error
	// ReadLink returns the destination of the symbolic link at name.
	// Equivalent to [ufs.ReadFS.ReadLink].
	ReadLink(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error)
	// GetFileSystemInfo describes the file system itself. Equivalent to
	// [ufs.ReadFS.URI] and [ufs.ReadFS.String].
	GetFileSystemInfo(context.Context, *GetFileSystemInfoRequest) (*FileSystemInfo, error)
	mustEmbedUnimplementedReadFSServer()
}

// UnimplementedReadFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadFSServer struct{}

func (UnimplementedReadFSServer) GetFile(context.Context, *GetFileRequest) (*File, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedReadFSServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedReadFSServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedReadFSServer) ReadLink(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLink not implemented")
}
func (UnimplementedReadFSServer) GetFileSystemInfo(context.Context, *GetFileSystemInfoRequest) (*FileSystemInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileSystemInfo not implemented")
}
func (UnimplementedReadFSServer) mustEmbedUnimplementedReadFSServer() {}
func (UnimplementedReadFSServer) testEmbeddedByValue()                {}

// UnsafeReadFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadFSServer will
// result in compilation errors.
type UnsafeReadFSServer interface {
	mustEmbedUnimplementedReadFSServer()
}

func RegisterReadFSServer(s grpc.ServiceRegistrar, srv ReadFSServer) {
	// If the following call panics, it indicates UnimplementedReadFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadFS_ServiceDesc, srv)
}

func _ReadFS_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadFSServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadFS_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadFSServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadFS_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadFSServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadFS_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadFSServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadFS_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReadFSServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, ReadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReadFS_ReadFileServer = grpc.ServerStreamingServer[ReadFileResponse]

func _ReadFS_ReadLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadFSServer).ReadLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadFS_ReadLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadFSServer).ReadLink(ctx, req.(*ReadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadFS_GetFileSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadFSServer).GetFileSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadFS_GetFileSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadFSServer).GetFileSystemInfo(ctx, req.(*GetFileSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadFS_ServiceDesc is the grpc.ServiceDesc for ReadFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudfra.ufs.ReadFS",
	HandlerType: (*ReadFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _ReadFS_GetFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _ReadFS_ListFiles_Handler,
		},
		{
			MethodName: "ReadLink",
			Handler:    _ReadFS_ReadLink_Handler,
		},
		{
			MethodName: "GetFileSystemInfo",
			Handler:    _ReadFS_GetFileSystemInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _ReadFS_ReadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ufs.proto",
}
