// Copyright 2026 Jeremy Edwards
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/writelog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Op is the kind of mutation.
type WriteLogEntry_Op int32

const (
	// Unset. Never recorded.
	WriteLogEntry_OP_UNSPECIFIED WriteLogEntry_Op = 0
	// Write the file's full content, creating missing parent directories.
	WriteLogEntry_OP_PUT WriteLogEntry_Op = 1
	// Create the directory and any missing parents, like MkdirAll.
	WriteLogEntry_OP_MKDIR WriteLogEntry_Op = 2
	// Remove the path and everything below it, like RemoveAll. Removing a
	// path that does not exist succeeds.
	WriteLogEntry_OP_REMOVE_ALL WriteLogEntry_Op = 3
)

// Enum value maps for WriteLogEntry_Op.
var (
	WriteLogEntry_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_PUT",
		2: "OP_MKDIR",
		3: "OP_REMOVE_ALL",
	}
	WriteLogEntry_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_PUT":         1,
		"OP_MKDIR":       2,
		"OP_REMOVE_ALL":  3,
	}
)

func (x WriteLogEntry_Op) Enum() *WriteLogEntry_Op {
	p := new(WriteLogEntry_Op)
	*p = x
	return p
}

func (x WriteLogEntry_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteLogEntry_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_writelog_proto_enumTypes[0].Descriptor()
}

func (WriteLogEntry_Op) Type() protoreflect.EnumType {
	return &file_proto_writelog_proto_enumTypes[0]
}

func (x WriteLogEntry_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteLogEntry_Op.Descriptor instead.
func (WriteLogEntry_Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_writelog_proto_rawDescGZIP(), []int{0, 0}
}

// WriteLogEntry is one mutation recorded by a write log
// (drivers/common/writelog). Entries are replayed in order against another
// file system to reproduce the mutations. WriteLogEntry is not part of the
// RPC surface.
type WriteLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mutation.
	Op WriteLogEntry_Op `protobuf:"varint,1,opt,name=op,enum=cloudfra.ufs.WriteLogEntry_Op" json:"op,omitempty"`
	// The fs.ValidPath name the mutation applies to.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// File mode bits, as defined by Go's io/fs.FileMode.
	Mode uint32 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	// The modification time of the file or directory after the mutation.
	ModTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime" json:"mod_time,omitempty"`
	// OP_PUT only: the content length in bytes.
	Size int64 `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	// OP_PUT only: the content. Empty until the payload is attached; a write
	// log may reference the payload in its source file system instead.
	Content       []byte `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteLogEntry) Reset() {
	*x = WriteLogEntry{}
	mi := &file_proto_writelog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLogEntry) ProtoMessage() {}

func (x *WriteLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_writelog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLogEntry.ProtoReflect.Descriptor instead.
func (*WriteLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_writelog_proto_rawDescGZIP(), []int{0}
}

func (x *WriteLogEntry) GetOp() WriteLogEntry_Op {
	if x != nil {
		return x.Op
	}
	return WriteLogEntry_OP_UNSPECIFIED
}

func (x *WriteLogEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WriteLogEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WriteLogEntry) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *WriteLogEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteLogEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_writelog_proto protoreflect.FileDescriptor

const file_proto_writelog_proto_rawDesc = "" +
	"\n" +
	"\x14proto/writelog.proto\x12\fcloudfra.ufs\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n" +
	"\rWriteLogEntry\x12.\n" +
	"\x02op\x18\x01 \x01(\x0e2\x1e.cloudfra.ufs.WriteLogEntry.OpR\x02op\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\"E\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x01\x12\f\n" +
	"\bOP_MKDIR\x10\x02\x12\x11\n" +
	"\rOP_REMOVE_ALL\x10\x03B)Z\x1dgithub.com/cloudfra/ufs/proto\x92\x03\a\xd2>\x02\x10\x01\b\x02b\beditionsp\xe9\a"

var (
	file_proto_writelog_proto_rawDescOnce sync.Once
	file_proto_writelog_proto_rawDescData []byte
)

func file_proto_writelog_proto_rawDescGZIP() []byte {
	file_proto_writelog_proto_rawDescOnce.Do(func() {
		file_proto_writelog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_writelog_proto_rawDesc), len(file_proto_writelog_proto_rawDesc)))
	})
	return file_proto_writelog_proto_rawDescData
}

var file_proto_writelog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_writelog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_writelog_proto_goTypes = []any{
	(WriteLogEntry_Op)(0),         // 0: cloudfra.ufs.WriteLogEntry.Op
	(*WriteLogEntry)(nil),         // 1: cloudfra.ufs.WriteLogEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_writelog_proto_depIdxs = []int32{
	0, // 0: cloudfra.ufs.WriteLogEntry.op:type_name -> cloudfra.ufs.WriteLogEntry.Op
	2, // 1: cloudfra.ufs.WriteLogEntry.mod_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_writelog_proto_init() }
func file_proto_writelog_proto_init() {
	if File_proto_writelog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_writelog_proto_rawDesc), len(file_proto_writelog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_writelog_proto_goTypes,
		DependencyIndexes: file_proto_writelog_proto_depIdxs,
		EnumInfos:         file_proto_writelog_proto_enumTypes,
		MessageInfos:      file_proto_writelog_proto_msgTypes,
	}.Build()
	File_proto_writelog_proto = out.File
	file_proto_writelog_proto_goTypes = nil
	file_proto_writelog_proto_depIdxs = nil
}
